# ==============================================================================
# github.yml
# ------------------------------------------------------------------------------
#
# If you are deploying to GH pages, set the baseURL in this file to
# whatever your GH Pages URL will be (username.github.io/project-name/, for
# example) and make sure canonifyURLs is set to true. You will also need
# to check the `site/` folder (or whatever you are using for output)
# into version control. Then you can run the deploy script at bin/deploy.sh
# to push files to Github.

# Use these settings for GH Pages

baseURL: "https://gettypubs.github.io/quire-starter/" # Needs trailing slash
canonifyURLs: false
