# ==============================================================================
# netlify.yml
# ------------------------------------------------------------------------------
#
# Deployment config for https://www.netlify.com/
# The baseURL should be updated to your Netlify subdomain
#
# You will also need to add a `netlify.toml` file with the following:
# [build]
#   publish = "site"
#   command = "hugo --config=config.yml,config/web.yml,config/environments/netlify.yml"
#   HUGO_VERSION = "0.31"

# Use these settings for Netlify
#

baseURL: "https://quire-demo.netlify.com"
relativeURLs: true
